// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Alarm struct {
	Id       string `json:"_id"`
	Key      string `json:"key"`
	Msg      string `json:"msg"`
	Archived bool   `json:"archived"`
}

type Client struct {
	Mac      string `json:"mac"`
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
	Ip       string `json:"ip"`
	Oui      string `json:"oui"`
	IsWired  bool   `json:"is_wired"`
	Network  string `json:"network"`
	Uptime   int    `json:"uptime"`
	RxBytes  int    `json:"rx_bytes"`
	TxBytes  int    `json:"tx_bytes"`
	Signal   int    `json:"signal"`
}

type Device struct {
	Mac     string `json:"mac"`
	Name    string `json:"name"`
	Model   string `json:"model"`
	Type    string `json:"type"`
	Ip      string `json:"ip"`
	Version string `json:"version"`
	State   int    `json:"state"`
	Uptime  int    `json:"uptime"`
	Adopted bool   `json:"adopted"`
}

type FirewallGroup struct {
	Id        string `json:"_id"`
	Name      string `json:"name"`
	GroupType string `json:"group_type"`
}

type FirewallPolicy struct {
	Id      string `json:"_id"`
	Name    string `json:"name"`
	Action  string `json:"action"`
	Enabled bool   `json:"enabled"`
}

type Network struct {
	Id       string `json:"_id"`
	Name     string `json:"name"`
	Purpose  string `json:"purpose"`
	IpSubnet string `json:"ip_subnet"`
	Vlan     string `json:"vlan"`
	Enabled  bool   `json:"enabled"`
}

type PortForward struct {
	Id      string `json:"_id"`
	Name    string `json:"name"`
	DstPort string `json:"dst_port"`
	Fwd     string `json:"fwd"`
	Enabled bool   `json:"enabled"`
}

type PortProfile struct {
	Id      string `json:"_id"`
	Name    string `json:"name"`
	Forward string `json:"forward"`
}

type Route struct {
	Id      string `json:"_id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
}

type UserGroup struct {
	Id             string `json:"_id"`
	Name           string `json:"name"`
	QosRateMaxDown int    `json:"qos_rate_max_down"`
	QosRateMaxUp   int    `json:"qos_rate_max_up"`
}

type Voucher struct {
	Id    string `json:"_id"`
	Code  string `json:"code"`
	Quota int    `json:"quota"`
	Used  int    `json:"used"`
}

type Wlan struct {
	Id            string `json:"_id"`
	Name          string `json:"name"`
	Security      string `json:"security"`
	Enabled       bool   `json:"enabled"`
	WlanBand      string `json:"wlan_band"`
	NetworkconfId string `json:"networkconf_id"`
}
