// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("unifi-network_search",
			mcplib.WithDescription("Search the unifi-network API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("unifi-network_execute",
			mcplib.WithDescription("Execute one unifi-network API endpoint by its endpoint_id (from unifi-network_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by unifi-network_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName string
	WireName   string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "acl-rules.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/acl-rules",
		Summary:        "Create a MAC ACL rule. Provide the rule object via --body-json",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("acl-rules", "create", "Create a MAC ACL rule. Provide the rule object via --body-json", "/v2/api/site/__SITE__/acl-rules"),
	},
	{
		ID:             "acl-rules.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/acl-rules/{id}",
		Summary:        "Delete a MAC ACL rule by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("acl-rules", "delete", "Delete a MAC ACL rule by id", "/v2/api/site/__SITE__/acl-rules/{id}"),
	},
	{
		ID:             "acl-rules.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/acl-rules",
		Summary:        "List MAC ACL rules (Policy Engine) for L2 access control within a VLAN",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("acl-rules", "list", "List MAC ACL rules (Policy Engine) for L2 access control within a VLAN", "/v2/api/site/__SITE__/acl-rules"),
	},
	{
		ID:             "acl-rules.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/acl-rules/{id}",
		Summary:        "Update a MAC ACL rule by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("acl-rules", "update", "Update a MAC ACL rule by id", "/v2/api/site/__SITE__/acl-rules/{id}"),
	},
	{
		ID:             "ap-groups.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/apgroups",
		Summary:        "Create an AP group",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("ap-groups", "create", "Create an AP group", "/v2/api/site/__SITE__/apgroups"),
	},
	{
		ID:             "ap-groups.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/apgroups/{id}",
		Summary:        "Delete an AP group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("ap-groups", "delete", "Delete an AP group by id", "/v2/api/site/__SITE__/apgroups/{id}"),
	},
	{
		ID:             "ap-groups.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/apgroups",
		Summary:        "List AP groups with member APs and WLAN memberships",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("ap-groups", "list", "List AP groups with member APs and WLAN memberships", "/v2/api/site/__SITE__/apgroups"),
	},
	{
		ID:             "ap-groups.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/apgroups/{id}",
		Summary:        "Update an AP group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("ap-groups", "update", "Update an AP group by id", "/v2/api/site/__SITE__/apgroups/{id}"),
	},
	{
		ID:             "client-groups.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/network-members-group",
		Summary:        "Create a client group (members = list of MAC addresses)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("client-groups", "create", "Create a client group (members = list of MAC addresses)", "/v2/api/site/__SITE__/network-members-group"),
	},
	{
		ID:             "client-groups.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/network-members-group/{id}",
		Summary:        "Delete a client group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("client-groups", "delete", "Delete a client group by id", "/v2/api/site/__SITE__/network-members-group/{id}"),
	},
	{
		ID:             "client-groups.get",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/network-members-group/{id}",
		Summary:        "Get a client group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("client-groups", "get", "Get a client group by id", "/v2/api/site/__SITE__/network-members-group/{id}"),
	},
	{
		ID:             "client-groups.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/network-members-groups",
		Summary:        "List client groups (MAC member groups used by OON policies and firewall rules)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("client-groups", "list", "List client groups (MAC member groups used by OON policies and firewall rules)", "/v2/api/site/__SITE__/network-members-groups"),
	},
	{
		ID:             "client-groups.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/network-members-group/{id}",
		Summary:        "Update a client group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("client-groups", "update", "Update a client group by id", "/v2/api/site/__SITE__/network-members-group/{id}"),
	},
	{
		ID:             "clients.known",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/user",
		Summary:        "List all known clients in controller history (including offline), with fixed-IP and note settings",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("clients", "known", "List all known clients in controller history (including offline), with fixed-IP and note settings", "/api/s/__SITE__/rest/user"),
	},
	{
		ID:             "clients.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/sta",
		Summary:        "List currently connected clients (wired and wireless) with mac, ip, status, signal and SSID",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("clients", "list", "List currently connected clients (wired and wireless) with mac, ip, status, signal and SSID", "/api/s/__SITE__/stat/sta"),
	},
	{
		ID:             "content-filters.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/content-filtering/{id}",
		Summary:        "Delete a content filtering profile by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("content-filters", "delete", "Delete a content filtering profile by id", "/v2/api/site/__SITE__/content-filtering/{id}"),
	},
	{
		ID:             "content-filters.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/content-filtering",
		Summary:        "List content filtering profiles (category blocking, safe search, allow/block lists).",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("content-filters", "list", "List content filtering profiles (category blocking, safe search, allow/block lists).", "/v2/api/site/__SITE__/content-filtering"),
	},
	{
		ID:             "content-filters.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/content-filtering/{id}",
		Summary:        "Update a content filtering profile by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("content-filters", "update", "Update a content filtering profile by id", "/v2/api/site/__SITE__/content-filtering/{id}"),
	},
	{
		ID:             "devices.channels",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/current-channel",
		Summary:        "List allowed RF channels for the site's regulatory domain (per band, with DFS and max power)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("devices", "channels", "List allowed RF channels for the site's regulatory domain (per band, with DFS and max power)", "/api/s/__SITE__/stat/current-channel"),
	},
	{
		ID:             "devices.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/device/{mac}",
		Summary:        "Get one device's full object by MAC (radio/port/outlet tables, system stats, WAN info)",
		Positional:     []string{"mac"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("devices", "get", "Get one device's full object by MAC (radio/port/outlet tables, system stats, WAN info)", "/api/s/__SITE__/stat/device/{mac}"),
	},
	{
		ID:             "devices.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/device",
		Summary:        "List adopted devices with mac, name, model, ip, version, uptime, state and uplink",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("devices", "list", "List adopted devices with mac, name, model, ip, version, uptime, state and uplink", "/api/s/__SITE__/stat/device"),
	},
	{
		ID:             "dns-records.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/static-dns",
		Summary:        "Create a static DNS record",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dns-records", "create", "Create a static DNS record", "/v2/api/site/__SITE__/static-dns"),
	},
	{
		ID:             "dns-records.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/static-dns/{id}",
		Summary:        "Delete a static DNS record by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dns-records", "delete", "Delete a static DNS record by id", "/v2/api/site/__SITE__/static-dns/{id}"),
	},
	{
		ID:             "dns-records.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/static-dns",
		Summary:        "List static DNS records (hostname, value, type, enabled, ttl)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dns-records", "list", "List static DNS records (hostname, value, type, enabled, ttl)", "/v2/api/site/__SITE__/static-dns"),
	},
	{
		ID:             "dns-records.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/static-dns/{id}",
		Summary:        "Update a static DNS record by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dns-records", "update", "Update a static DNS record by id", "/v2/api/site/__SITE__/static-dns/{id}"),
	},
	{
		ID:             "dpi.applications",
		Method:         "GET",
		Path:           "/proxy/network/integration/v1/dpi/applications",
		Summary:        "List DPI applications (Integration API; requires UNIFI_API_KEY)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "limit", WireName: "limit"}, {PublicName: "offset", WireName: "offset"}},
		keywords:       codeOrchKeywords("dpi", "applications", "List DPI applications (Integration API; requires UNIFI_API_KEY)", "/proxy/network/integration/v1/dpi/applications"),
	},
	{
		ID:             "dpi.categories",
		Method:         "GET",
		Path:           "/proxy/network/integration/v1/dpi/categories",
		Summary:        "List DPI application categories (Integration API; requires UNIFI_API_KEY)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "limit", WireName: "limit"}, {PublicName: "offset", WireName: "offset"}},
		keywords:       codeOrchKeywords("dpi", "categories", "List DPI application categories (Integration API; requires UNIFI_API_KEY)", "/proxy/network/integration/v1/dpi/categories"),
	},
	{
		ID:             "events.alarms",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/alarm",
		Summary:        "List active alarms (security alerts, connectivity issues, firmware warnings)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("events", "alarms", "List active alarms (security alerts, connectivity issues, firmware warnings)", "/api/s/__SITE__/stat/alarm"),
	},
	{
		ID:             "events.alarms-archived",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/alarm",
		Summary:        "List archived (historical) alarms",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "archived", WireName: "archived"}},
		keywords:       codeOrchKeywords("events", "alarms-archived", "List archived (historical) alarms", "/api/s/__SITE__/stat/alarm"),
	},
	{
		ID:             "firewall-groups.create",
		Method:         "POST",
		Path:           "/api/s/__SITE__/rest/firewallgroup",
		Summary:        "Create a firewall group (group_type is immutable after creation)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-groups", "create", "Create a firewall group (group_type is immutable after creation)", "/api/s/__SITE__/rest/firewallgroup"),
	},
	{
		ID:             "firewall-groups.delete",
		Method:         "DELETE",
		Path:           "/api/s/__SITE__/rest/firewallgroup/{id}",
		Summary:        "Delete a firewall group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-groups", "delete", "Delete a firewall group by id", "/api/s/__SITE__/rest/firewallgroup/{id}"),
	},
	{
		ID:             "firewall-groups.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/firewallgroup/{id}",
		Summary:        "Get a firewall group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-groups", "get", "Get a firewall group by id", "/api/s/__SITE__/rest/firewallgroup/{id}"),
	},
	{
		ID:             "firewall-groups.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/firewallgroup",
		Summary:        "List firewall groups (address-group, ipv6-address-group, port-group)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-groups", "list", "List firewall groups (address-group, ipv6-address-group, port-group)", "/api/s/__SITE__/rest/firewallgroup"),
	},
	{
		ID:             "firewall-groups.update",
		Method:         "PUT",
		Path:           "/api/s/__SITE__/rest/firewallgroup/{id}",
		Summary:        "Update a firewall group by id (PUT replaces the full object)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-groups", "update", "Update a firewall group by id (PUT replaces the full object)", "/api/s/__SITE__/rest/firewallgroup/{id}"),
	},
	{
		ID:             "firewall-policies.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/firewall-policies",
		Summary:        "Create a V2 firewall policy. Provide the full policy object via --body-json",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-policies", "create", "Create a V2 firewall policy. Provide the full policy object via --body-json", "/v2/api/site/__SITE__/firewall-policies"),
	},
	{
		ID:             "firewall-policies.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/firewall-policies/{id}",
		Summary:        "Delete a firewall policy by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-policies", "delete", "Delete a firewall policy by id", "/v2/api/site/__SITE__/firewall-policies/{id}"),
	},
	{
		ID:             "firewall-policies.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/firewall-policies",
		Summary:        "List V2 zone-based firewall policies (zone targeting, action, enabled, index)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-policies", "list", "List V2 zone-based firewall policies (zone targeting, action, enabled, index)", "/v2/api/site/__SITE__/firewall-policies"),
	},
	{
		ID:             "firewall-policies.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/firewall-policies/{id}",
		Summary:        "Update a firewall policy by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-policies", "update", "Update a firewall policy by id", "/v2/api/site/__SITE__/firewall-policies/{id}"),
	},
	{
		ID:             "firewall-zones.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/firewall/zone-matrix",
		Summary:        "List firewall zones and the zone matrix",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("firewall-zones", "list", "List firewall zones and the zone matrix", "/v2/api/site/__SITE__/firewall/zone-matrix"),
	},
	{
		ID:             "networks.create",
		Method:         "POST",
		Path:           "/api/s/__SITE__/rest/networkconf",
		Summary:        "Create a network/VLAN. Pass the full network object as --body-json or individual fields",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("networks", "create", "Create a network/VLAN. Pass the full network object as --body-json or individual fields", "/api/s/__SITE__/rest/networkconf"),
	},
	{
		ID:             "networks.delete",
		Method:         "DELETE",
		Path:           "/api/s/__SITE__/rest/networkconf/{id}",
		Summary:        "Delete a network by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("networks", "delete", "Delete a network by id", "/api/s/__SITE__/rest/networkconf/{id}"),
	},
	{
		ID:             "networks.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/networkconf/{id}",
		Summary:        "Get a network's full configuration by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("networks", "get", "Get a network's full configuration by id", "/api/s/__SITE__/rest/networkconf/{id}"),
	},
	{
		ID:             "networks.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/networkconf",
		Summary:        "List configured networks (LAN/WAN/VLAN) with name, purpose, subnet, VLAN id and DHCP settings",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("networks", "list", "List configured networks (LAN/WAN/VLAN) with name, purpose, subnet, VLAN id and DHCP settings", "/api/s/__SITE__/rest/networkconf"),
	},
	{
		ID:             "networks.update",
		Method:         "PUT",
		Path:           "/api/s/__SITE__/rest/networkconf/{id}",
		Summary:        "Update a network by id (PUT replaces the resource; fetch+merge with 'get' first)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("networks", "update", "Update a network by id (PUT replaces the resource; fetch+merge with 'get' first)", "/api/s/__SITE__/rest/networkconf/{id}"),
	},
	{
		ID:             "oon-policies.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/object-oriented-network-config",
		Summary:        "Create an OON policy. Provide the full nested policy object via --body-json",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("oon-policies", "create", "Create an OON policy. Provide the full nested policy object via --body-json", "/v2/api/site/__SITE__/object-oriented-network-config"),
	},
	{
		ID:             "oon-policies.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/object-oriented-network-config/{id}",
		Summary:        "Delete an OON policy by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("oon-policies", "delete", "Delete an OON policy by id", "/v2/api/site/__SITE__/object-oriented-network-config/{id}"),
	},
	{
		ID:             "oon-policies.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/object-oriented-network-configs",
		Summary:        "List OON policies (internet access schedules, app blocking, QoS, policy routing)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("oon-policies", "list", "List OON policies (internet access schedules, app blocking, QoS, policy routing)", "/v2/api/site/__SITE__/object-oriented-network-configs"),
	},
	{
		ID:             "oon-policies.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/object-oriented-network-config/{id}",
		Summary:        "Update an OON policy by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("oon-policies", "update", "Update an OON policy by id", "/v2/api/site/__SITE__/object-oriented-network-config/{id}"),
	},
	{
		ID:             "port-forwards.create",
		Method:         "POST",
		Path:           "/api/s/__SITE__/rest/portforward",
		Summary:        "Create a port forwarding rule",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-forwards", "create", "Create a port forwarding rule", "/api/s/__SITE__/rest/portforward"),
	},
	{
		ID:             "port-forwards.delete",
		Method:         "DELETE",
		Path:           "/api/s/__SITE__/rest/portforward/{id}",
		Summary:        "Delete a port forwarding rule by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-forwards", "delete", "Delete a port forwarding rule by id", "/api/s/__SITE__/rest/portforward/{id}"),
	},
	{
		ID:             "port-forwards.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/portforward/{id}",
		Summary:        "Get a port forwarding rule by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-forwards", "get", "Get a port forwarding rule by id", "/api/s/__SITE__/rest/portforward/{id}"),
	},
	{
		ID:             "port-forwards.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/portforward",
		Summary:        "List port forwarding rules",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-forwards", "list", "List port forwarding rules", "/api/s/__SITE__/rest/portforward"),
	},
	{
		ID:             "port-forwards.update",
		Method:         "PUT",
		Path:           "/api/s/__SITE__/rest/portforward/{id}",
		Summary:        "Update a port forwarding rule by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-forwards", "update", "Update a port forwarding rule by id", "/api/s/__SITE__/rest/portforward/{id}"),
	},
	{
		ID:             "port-profiles.create",
		Method:         "POST",
		Path:           "/api/s/__SITE__/rest/portconf",
		Summary:        "Create a port profile (forward: native | all | customize | disabled)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-profiles", "create", "Create a port profile (forward: native | all | customize | disabled)", "/api/s/__SITE__/rest/portconf"),
	},
	{
		ID:             "port-profiles.delete",
		Method:         "DELETE",
		Path:           "/api/s/__SITE__/rest/portconf/{id}",
		Summary:        "Delete a port profile by id (system profiles cannot be deleted)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-profiles", "delete", "Delete a port profile by id (system profiles cannot be deleted)", "/api/s/__SITE__/rest/portconf/{id}"),
	},
	{
		ID:             "port-profiles.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/portconf/{id}",
		Summary:        "Get a port profile by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-profiles", "get", "Get a port profile by id", "/api/s/__SITE__/rest/portconf/{id}"),
	},
	{
		ID:             "port-profiles.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/portconf",
		Summary:        "List port profiles (VLAN, isolation, PoE, STP, 802.1X, storm control)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-profiles", "list", "List port profiles (VLAN, isolation, PoE, STP, 802.1X, storm control)", "/api/s/__SITE__/rest/portconf"),
	},
	{
		ID:             "port-profiles.update",
		Method:         "PUT",
		Path:           "/api/s/__SITE__/rest/portconf/{id}",
		Summary:        "Update a port profile by id (system profiles with attr_no_edit cannot be modified)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("port-profiles", "update", "Update a port profile by id (system profiles with attr_no_edit cannot be modified)", "/api/s/__SITE__/rest/portconf/{id}"),
	},
	{
		ID:             "qos-rules.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/qos-rules",
		Summary:        "Create a QoS rule. Provide the rule object via --body-json",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("qos-rules", "create", "Create a QoS rule. Provide the rule object via --body-json", "/v2/api/site/__SITE__/qos-rules"),
	},
	{
		ID:             "qos-rules.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/qos-rules/{id}",
		Summary:        "Delete a QoS rule by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("qos-rules", "delete", "Delete a QoS rule by id", "/v2/api/site/__SITE__/qos-rules/{id}"),
	},
	{
		ID:             "qos-rules.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/qos-rules",
		Summary:        "List QoS rules for the current site",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("qos-rules", "list", "List QoS rules for the current site", "/v2/api/site/__SITE__/qos-rules"),
	},
	{
		ID:             "qos-rules.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/qos-rules/{id}",
		Summary:        "Update a QoS rule by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("qos-rules", "update", "Update a QoS rule by id", "/v2/api/site/__SITE__/qos-rules/{id}"),
	},
	{
		ID:             "routes.active",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/routing",
		Summary:        "List the active routing table on the gateway (user-defined and system routes; may be empty on some firmware)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("routes", "active", "List the active routing table on the gateway (user-defined and system routes; may be empty on some firmware)", "/api/s/__SITE__/stat/routing"),
	},
	{
		ID:             "routes.create",
		Method:         "POST",
		Path:           "/api/s/__SITE__/rest/routing",
		Summary:        "Create a static route (destination CIDR + next-hop IP)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("routes", "create", "Create a static route (destination CIDR + next-hop IP)", "/api/s/__SITE__/rest/routing"),
	},
	{
		ID:             "routes.delete",
		Method:         "DELETE",
		Path:           "/api/s/__SITE__/rest/routing/{id}",
		Summary:        "Delete a static route by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("routes", "delete", "Delete a static route by id", "/api/s/__SITE__/rest/routing/{id}"),
	},
	{
		ID:             "routes.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/routing/{id}",
		Summary:        "Get a static route by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("routes", "get", "Get a static route by id", "/api/s/__SITE__/rest/routing/{id}"),
	},
	{
		ID:             "routes.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/routing",
		Summary:        "List user-defined static routes (name, destination, next-hop, status)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("routes", "list", "List user-defined static routes (name, destination, next-hop, status)", "/api/s/__SITE__/rest/routing"),
	},
	{
		ID:             "routes.update",
		Method:         "PUT",
		Path:           "/api/s/__SITE__/rest/routing/{id}",
		Summary:        "Update a static route by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("routes", "update", "Update a static route by id", "/api/s/__SITE__/rest/routing/{id}"),
	},
	{
		ID:             "stats.dashboard",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/aggregated-dashboard",
		Summary:        "Pre-aggregated site dashboard (health, device/client counts, ISP status)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "history-seconds", WireName: "historySeconds"}},
		keywords:       codeOrchKeywords("stats", "dashboard", "Pre-aggregated site dashboard (health, device/client counts, ISP status)", "/v2/api/site/__SITE__/aggregated-dashboard"),
	},
	{
		ID:             "stats.dpi",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/dpi",
		Summary:        "Deep Packet Inspection stats (applications and categories) for the site",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("stats", "dpi", "Deep Packet Inspection stats (applications and categories) for the site", "/api/s/__SITE__/stat/dpi"),
	},
	{
		ID:             "system.health",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/health",
		Summary:        "Per-subsystem health for WAN, LAN, WLAN and VPN with device and user counts",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("system", "health", "Per-subsystem health for WAN, LAN, WLAN and VPN with device and user counts", "/api/s/__SITE__/stat/health"),
	},
	{
		ID:             "system.info",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/sysinfo",
		Summary:        "Controller version, uptime, hostname, CPU/memory and update availability",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("system", "info", "Controller version, uptime, hostname, CPU/memory and update availability", "/api/s/__SITE__/stat/sysinfo"),
	},
	{
		ID:             "system.settings",
		Method:         "GET",
		Path:           "/api/s/__SITE__/get/setting/{section}",
		Summary:        "Get a settings section (e.g. mgmt, snmp, super_mgmt, guest_access, country)",
		Positional:     []string{"section"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("system", "settings", "Get a settings section (e.g. mgmt, snmp, super_mgmt, guest_access, country)", "/api/s/__SITE__/get/setting/{section}"),
	},
	{
		ID:             "system.sites",
		Method:         "GET",
		Path:           "/api/self/sites",
		Summary:        "List all sites visible to the authenticated account (with their site keys)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("system", "sites", "List all sites visible to the authenticated account (with their site keys)", "/api/self/sites"),
	},
	{
		ID:             "system.status",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/status",
		Summary:        "Controller status (server version, up flag)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("system", "status", "Controller status (server version, up flag)", "/api/s/__SITE__/stat/status"),
	},
	{
		ID:             "traffic-routes.create",
		Method:         "POST",
		Path:           "/v2/api/site/__SITE__/trafficroutes",
		Summary:        "Create a traffic route. Provide the route object via --body-json",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("traffic-routes", "create", "Create a traffic route. Provide the route object via --body-json", "/v2/api/site/__SITE__/trafficroutes"),
	},
	{
		ID:             "traffic-routes.delete",
		Method:         "DELETE",
		Path:           "/v2/api/site/__SITE__/trafficroutes/{id}",
		Summary:        "Delete a traffic route by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("traffic-routes", "delete", "Delete a traffic route by id", "/v2/api/site/__SITE__/trafficroutes/{id}"),
	},
	{
		ID:             "traffic-routes.list",
		Method:         "GET",
		Path:           "/v2/api/site/__SITE__/trafficroutes",
		Summary:        "List traffic routes (policy-based routing by domain/IP/region/device, often for VPN)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("traffic-routes", "list", "List traffic routes (policy-based routing by domain/IP/region/device, often for VPN)", "/v2/api/site/__SITE__/trafficroutes"),
	},
	{
		ID:             "traffic-routes.update",
		Method:         "PUT",
		Path:           "/v2/api/site/__SITE__/trafficroutes/{id}",
		Summary:        "Update a traffic route by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("traffic-routes", "update", "Update a traffic route by id", "/v2/api/site/__SITE__/trafficroutes/{id}"),
	},
	{
		ID:             "usergroups.create",
		Method:         "POST",
		Path:           "/api/s/__SITE__/rest/usergroup",
		Summary:        "Create a user group (bandwidth profile). Use -1 for unlimited",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("usergroups", "create", "Create a user group (bandwidth profile). Use -1 for unlimited", "/api/s/__SITE__/rest/usergroup"),
	},
	{
		ID:             "usergroups.delete",
		Method:         "DELETE",
		Path:           "/api/s/__SITE__/rest/usergroup/{id}",
		Summary:        "Delete a user group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("usergroups", "delete", "Delete a user group by id", "/api/s/__SITE__/rest/usergroup/{id}"),
	},
	{
		ID:             "usergroups.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/usergroup/{id}",
		Summary:        "Get a user group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("usergroups", "get", "Get a user group by id", "/api/s/__SITE__/rest/usergroup/{id}"),
	},
	{
		ID:             "usergroups.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/usergroup",
		Summary:        "List user groups (bandwidth profiles) with up/down speed caps in Kbps",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("usergroups", "list", "List user groups (bandwidth profiles) with up/down speed caps in Kbps", "/api/s/__SITE__/rest/usergroup"),
	},
	{
		ID:             "usergroups.update",
		Method:         "PUT",
		Path:           "/api/s/__SITE__/rest/usergroup/{id}",
		Summary:        "Update a user group by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("usergroups", "update", "Update a user group by id", "/api/s/__SITE__/rest/usergroup/{id}"),
	},
	{
		ID:             "vouchers.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/stat/voucher",
		Summary:        "List hotspot vouchers (codes, expiry, usage quota, bandwidth limits)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("vouchers", "list", "List hotspot vouchers (codes, expiry, usage quota, bandwidth limits)", "/api/s/__SITE__/stat/voucher"),
	},
	{
		ID:             "wlans.create",
		Method:         "POST",
		Path:           "/api/s/__SITE__/rest/wlanconf",
		Summary:        "Create a WLAN/SSID",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("wlans", "create", "Create a WLAN/SSID", "/api/s/__SITE__/rest/wlanconf"),
	},
	{
		ID:             "wlans.delete",
		Method:         "DELETE",
		Path:           "/api/s/__SITE__/rest/wlanconf/{id}",
		Summary:        "Delete a WLAN/SSID by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("wlans", "delete", "Delete a WLAN/SSID by id", "/api/s/__SITE__/rest/wlanconf/{id}"),
	},
	{
		ID:             "wlans.get",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/wlanconf/{id}",
		Summary:        "Get a WLAN's full configuration by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("wlans", "get", "Get a WLAN's full configuration by id", "/api/s/__SITE__/rest/wlanconf/{id}"),
	},
	{
		ID:             "wlans.list",
		Method:         "GET",
		Path:           "/api/s/__SITE__/rest/wlanconf",
		Summary:        "List configured WLANs (SSIDs) with security, band, enabled state and network binding",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("wlans", "list", "List configured WLANs (SSIDs) with security, band, enabled state and network binding", "/api/s/__SITE__/rest/wlanconf"),
	},
	{
		ID:             "wlans.update",
		Method:         "PUT",
		Path:           "/api/s/__SITE__/rest/wlanconf/{id}",
		Summary:        "Update a WLAN by id (PUT replaces; fetch+merge with 'get' first)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("wlans", "update", "Update a WLAN by id (PUT replaces; fetch+merge with 'get' first)", "/api/s/__SITE__/rest/wlanconf/{id}"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call unifi-network_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call unifi-network_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", fmt.Sprintf("%v", v))
			delete(params, p)
		}
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = fmt.Sprintf("%v", v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		if enc := codeOrchSplitQuery(ep.QueryParams, params); enc != "" {
			sep := "?"
			if strings.Contains(path, "?") {
				sep = "&"
			}
			path += sep + enc
		}
	}

	hdrs := ep.HeaderOverrides
	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			data, err = c.GetWithHeaders(ctx, path, query, hdrs)
		} else {
			data, err = c.Get(ctx, path, query)
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// returns them URL-encoded for appending to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				uv.Set(q.WireName, fmt.Sprintf("%v", v))
				delete(params, key)
				break
			}
		}
	}
	return uv.Encode()
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
