// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAclRulesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "acl-rules",
		Short:       "MAC ACL rules (Layer 2 access control)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAclRulesCreateCmd(flags))
	cmd.AddCommand(newAclRulesDeleteCmd(flags))
	cmd.AddCommand(newAclRulesListCmd(flags))
	cmd.AddCommand(newAclRulesUpdateCmd(flags))
	return cmd
}
