// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newApGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "ap-groups",
		Short:       "AP groups (which APs broadcast which SSIDs)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newApGroupsCreateCmd(flags))
	cmd.AddCommand(newApGroupsDeleteCmd(flags))
	cmd.AddCommand(newApGroupsListCmd(flags))
	cmd.AddCommand(newApGroupsUpdateCmd(flags))
	return cmd
}
