// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"os"
	"unifi-network-pp-cli/internal/config"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Manage authentication for Unifi Network",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthSetTokenCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd prints concrete steps for getting a credential. Side-effect
// rule: print by default, --launch opt-in to open the URL, short-circuit when
// the verifier is running this in a sandboxed subprocess.
func newAuthSetupCmd(_ *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Print steps for obtaining a credential (use --launch to open the URL)",
		Example: "  unifi-network-pp-cli auth setup\n  unifi-network-pp-cli auth setup --launch",
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "Controller commands authenticate with a LOCAL controller admin login:")
			fmt.Fprintln(w, "  export UNIFI_HOST=<controller-ip>")
			fmt.Fprintln(w, "  export UNIFI_USERNAME=<local-admin>      # not a UI.com SSO login")
			fmt.Fprintln(w, "  export UNIFI_PASSWORD=<password>")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "Optional — only for the dpi/* and firewall-ordering commands (Integration API key):")
			fmt.Fprintln(w, "  export UNIFI_API_KEY=<key>               # UniFi UI > Control Plane > Integrations")
			fmt.Fprintln(w, "  unifi-network-pp-cli auth set-token <key>")
			if !launch {
				return nil
			}
			fmt.Fprintln(cmd.ErrOrStderr(), "no setup URL configured; cannot launch")
			return nil
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the setup URL in your default browser")
	return cmd
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  unifi-network-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			// "authenticated" reflects the PRIMARY controller login (the
			// username/password cookie session). The Integration API key alone
			// does NOT authenticate controller commands, so it is reported
			// separately and never on its own counts as authenticated.
			settings := config.LoadUnifiSettings(cfg)
			cookieReady := settings.HasCookieCredentials()
			apiKeyPresent := cfg.AuthHeader() != ""
			if flags.asJSON {
				out := map[string]any{
					"authenticated":               cookieReady,
					"controller_login_ready":      cookieReady,
					"integration_api_key_present": apiKeyPresent,
					"verified":                    false,
					"source":                      cfg.AuthSource,
					"config":                      cfg.Path,
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !cookieReady {
					return authErr(fmt.Errorf("controller login not configured: set UNIFI_HOST, UNIFI_USERNAME, UNIFI_PASSWORD"))
				}
				return nil
			}
			if !cookieReady {
				fmt.Fprintln(w, red("Controller login not configured"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Set a LOCAL controller admin (not a UI.com SSO login):")
				fmt.Fprintln(w, "  export UNIFI_HOST=<controller-ip> UNIFI_USERNAME=<admin> UNIFI_PASSWORD=<password>")
				if apiKeyPresent {
					fmt.Fprintln(w, "")
					fmt.Fprintln(w, "(An Integration API key is set — it covers the dpi/* and firewall-ordering commands only.)")
				}
				return authErr(fmt.Errorf("controller login not configured"))
			}

			fmt.Fprintln(w, green("Controller login configured (username/password, not verified — run `doctor`)"))
			fmt.Fprintf(w, "  Host: %s\n", settings.BaseURL())
			if apiKeyPresent {
				fmt.Fprintln(w, "  Integration API key: present (dpi/* and firewall-ordering)")
			}
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthSetTokenCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "set-token <token>",
		Short:   "Save the Integration API key (dpi/* & firewall-ordering only; controller commands use UNIFI_USERNAME/PASSWORD)",
		Example: "  unifi-network-pp-cli auth set-token YOUR_UNIFI_API_KEY",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Clear any legacy auth_header so AuthHeader() falls through to
			// the newly-saved credential. Without this, a pre-existing
			// auth_header value (common after regenerate) shadows the saved
			// token and set-token silently has no effect. Silent clear (no
			// log line): a masked-tail variant could leak token bytes through
			// scripted dogfood that captures stderr.
			cfg.AuthHeaderVal = ""
			// api_key auth: AuthHeader() reads the env-var-derived field, not
			// AccessToken. Writing the token to AccessToken via SaveTokens
			// would persist the bytes but leave doctor reporting "not
			// configured" — the slot the header builder consults stays empty.
			if err := cfg.SaveCredential(args[0]); err != nil {
				return configErr(fmt.Errorf("saving token: %w", err))
			}

			// JSON envelope: {saved, config_path}.
			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"saved":       true,
					"config_path": cfg.Path,
				}, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Token saved to %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  unifi-network-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("UNIFI_API_KEY") != "" {
				envStillSet = "UNIFI_API_KEY"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
