// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newClientGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "client-groups",
		Short:       "Client groups (network member groups for OON/firewall)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newClientGroupsCreateCmd(flags))
	cmd.AddCommand(newClientGroupsDeleteCmd(flags))
	cmd.AddCommand(newClientGroupsGetCmd(flags))
	cmd.AddCommand(newClientGroupsListCmd(flags))
	cmd.AddCommand(newClientGroupsUpdateCmd(flags))
	return cmd
}
