// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContentFiltersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "content-filters",
		Short:       "Content filtering profiles (DNS-based blocking, safe search)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newContentFiltersDeleteCmd(flags))
	cmd.AddCommand(newContentFiltersListCmd(flags))
	cmd.AddCommand(newContentFiltersUpdateCmd(flags))
	return cmd
}
