// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDevicesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "devices",
		Short:       "Adopted UniFi devices (APs, switches, gateways, PDUs)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDevicesChannelsCmd(flags))
	cmd.AddCommand(newDevicesGetCmd(flags))
	cmd.AddCommand(newDevicesListCmd(flags))
	return cmd
}
