// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDnsRecordsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dns-records",
		Short:       "Static DNS records (V2)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDnsRecordsCreateCmd(flags))
	cmd.AddCommand(newDnsRecordsDeleteCmd(flags))
	cmd.AddCommand(newDnsRecordsListCmd(flags))
	cmd.AddCommand(newDnsRecordsUpdateCmd(flags))
	return cmd
}
