// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDpiCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dpi",
		Short:       "DPI applications and categories (Integration API — requires UNIFI_API_KEY)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDpiApplicationsCmd(flags))
	cmd.AddCommand(newDpiCategoriesCmd(flags))
	return cmd
}
