// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFirewallPoliciesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "firewall-policies",
		Short:       "Zone-based firewall policies (V2)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFirewallPoliciesCreateCmd(flags))
	cmd.AddCommand(newFirewallPoliciesDeleteCmd(flags))
	cmd.AddCommand(newFirewallPoliciesListCmd(flags))
	cmd.AddCommand(newFirewallPoliciesUpdateCmd(flags))
	return cmd
}
