// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFirewallGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "firewall-groups",
		Short:       "Firewall address and port groups (reusable objects)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFirewallGroupsCreateCmd(flags))
	cmd.AddCommand(newFirewallGroupsDeleteCmd(flags))
	cmd.AddCommand(newFirewallGroupsGetCmd(flags))
	cmd.AddCommand(newFirewallGroupsListCmd(flags))
	cmd.AddCommand(newFirewallGroupsUpdateCmd(flags))
	return cmd
}
