// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOonPoliciesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "oon-policies",
		Short:       "OON policies (internet scheduling, app blocking, QoS, routing)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOonPoliciesCreateCmd(flags))
	cmd.AddCommand(newOonPoliciesDeleteCmd(flags))
	cmd.AddCommand(newOonPoliciesListCmd(flags))
	cmd.AddCommand(newOonPoliciesUpdateCmd(flags))
	return cmd
}
