// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPortProfilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "port-profiles",
		Short:       "List, get, create, update, and delete port profiles",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPortProfilesCreateCmd(flags))
	cmd.AddCommand(newPortProfilesDeleteCmd(flags))
	cmd.AddCommand(newPortProfilesGetCmd(flags))
	cmd.AddCommand(newPortProfilesListCmd(flags))
	cmd.AddCommand(newPortProfilesUpdateCmd(flags))
	return cmd
}
