// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPortForwardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "port-forwards",
		Short:       "Port forwarding rules (V1)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPortForwardsCreateCmd(flags))
	cmd.AddCommand(newPortForwardsDeleteCmd(flags))
	cmd.AddCommand(newPortForwardsGetCmd(flags))
	cmd.AddCommand(newPortForwardsListCmd(flags))
	cmd.AddCommand(newPortForwardsUpdateCmd(flags))
	return cmd
}
