// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newQosRulesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "qos-rules",
		Short:       "QoS / traffic-shaping rules (V2)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newQosRulesCreateCmd(flags))
	cmd.AddCommand(newQosRulesDeleteCmd(flags))
	cmd.AddCommand(newQosRulesListCmd(flags))
	cmd.AddCommand(newQosRulesUpdateCmd(flags))
	return cmd
}
