// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRoutesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "routes",
		Short:       "User-defined static routes (V1)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRoutesActiveCmd(flags))
	cmd.AddCommand(newRoutesCreateCmd(flags))
	cmd.AddCommand(newRoutesDeleteCmd(flags))
	cmd.AddCommand(newRoutesGetCmd(flags))
	cmd.AddCommand(newRoutesListCmd(flags))
	cmd.AddCommand(newRoutesUpdateCmd(flags))
	return cmd
}
