// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTrafficRoutesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "traffic-routes",
		Short:       "Traffic routes (policy-based routing, V2)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTrafficRoutesCreateCmd(flags))
	cmd.AddCommand(newTrafficRoutesDeleteCmd(flags))
	cmd.AddCommand(newTrafficRoutesListCmd(flags))
	cmd.AddCommand(newTrafficRoutesUpdateCmd(flags))
	return cmd
}
