// Copyright 2026 marcvstvllivs and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWlansCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "wlans",
		Short:       "Wireless LANs / SSIDs",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWlansCreateCmd(flags))
	cmd.AddCommand(newWlansDeleteCmd(flags))
	cmd.AddCommand(newWlansGetCmd(flags))
	cmd.AddCommand(newWlansListCmd(flags))
	cmd.AddCommand(newWlansUpdateCmd(flags))
	return cmd
}
